#服务端口
server:
  port: 18080
spring:
  application:
    name: tanhua-app-server
  redis:  #redis配置
    port: 6379
    host: localhost #redis地址，请自行配置
  cloud:  #nacos配置
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos地址，请自行配置
dubbo:    #dubbo配置
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
tanhua:
  sms: #短信服务配置，阿里云市场搜索“短信”自行购买与配置需要的属性
    appcode:
    minute:
    smsSignId:
    templateId:
  oss: #阿里云OSS服务
    #yourEndpoint填写Bucket所在地域对应的Endpoint。以华东1（杭州）为例，Endpoint填写为https://oss-cn-hangzhou.aliyuncs.com。
    endpoint:
    #阿里云账号AccessKey拥有所有API的访问权限，风险很高。强烈建议您创建并使用RAM用户进行API访问或日常运维，请登录RAM控制台创建RAM用户。
    accessKeyId:
    accessKeySecret:
    #填写Bucket名称，例如examplebucket。
    bucketName:
    #返回的文件访问地址，由endpoint和bucketName组成，例如https://examplebucket.oss-cn-hangzhou.aliyuncs.com/
    url:
